// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6ZCsDHORnWpf2iEIIgDOimy1FzFpG5M',
    appId: '1:556726737985:web:ce75b6e222a529a829fac0',
    messagingSenderId: '556726737985',
    projectId: 'foodtek-90f23',
    authDomain: 'foodtek-90f23.firebaseapp.com',
    storageBucket: 'foodtek-90f23.firebasestorage.app',
    measurementId: 'G-6K1RE8FH5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAi9eMjcecG-kT6Gu8Gwu-RGi_oXyN4aQ',
    appId: '1:556726737985:android:54c761f99aadb61d29fac0',
    messagingSenderId: '556726737985',
    projectId: 'foodtek-90f23',
    storageBucket: 'foodtek-90f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYOjUbg2AIGbuC0nvb7BXq5KEUDY_UEI',
    appId: '1:556726737985:ios:f1cce8d490917dbb29fac0',
    messagingSenderId: '556726737985',
    projectId: 'foodtek-90f23',
    storageBucket: 'foodtek-90f23.firebasestorage.app',
    iosBundleId: 'com.example.foodtek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYOjUbg2AIGbuC0nvb7BXq5KEUDY_UEI',
    appId: '1:556726737985:ios:f1cce8d490917dbb29fac0',
    messagingSenderId: '556726737985',
    projectId: 'foodtek-90f23',
    storageBucket: 'foodtek-90f23.firebasestorage.app',
    iosBundleId: 'com.example.foodtek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw6ZCsDHORnWpf2iEIIgDOimy1FzFpG5M',
    appId: '1:556726737985:web:6cf99b814b619b0f29fac0',
    messagingSenderId: '556726737985',
    projectId: 'foodtek-90f23',
    authDomain: 'foodtek-90f23.firebaseapp.com',
    storageBucket: 'foodtek-90f23.firebasestorage.app',
    measurementId: 'G-JBFEDGHX79',
  );
}
